version: 2.1
commands:
  checkout-test:
    steps:
      - run:
          name: Checkout tests
          command: cd .. && git clone -b ${TESTS_BRANCH} --single-branch git@github.com:twilio/selenoid-container-tests.git
  docker-login:
    steps:
      - run:
          name: Docker login
          command: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
  build-test-publish-image:
    parameters:
      publish:
        type: boolean
    steps:
      - run:
          name: Build image
          command: cd selenium && ./build_image.sh ${BROWSER_NAME} ${BROWSER_CHANNEL} "<< parameters.publish >>"
  show-image-info:
    steps:
      - run:
          name: Show image info
          command: |
            echo "Browser: ${BROWSER_NAME} "
            echo "Channel: ${BROWSER_CHANNEL}"
            docker inspect selenoid/${BROWSER_NAME}:${BROWSER_CHANNEL} | jq -r '.[0].Config.Labels'
jobs:
  build:
    machine:
      docker_layer_caching: false
      image: circleci/classic:201711-01
    environment:
      BROWSER_NAME: chrome
      BROWSER_CHANNEL: beta
      TESTS_BRANCH: develop
    parameters:
      publish:
        default: false
        type: boolean
    steps:
      - checkout
      - checkout-test
      - when:
          condition: << parameters.publish >>
          steps:
            - docker-login
      - build-test-publish-image:
          publish: << parameters.publish >>
      - show-image-info
workflows:
  version: 2
  build:
    jobs:
      - build:
          publish: false
  manual-build-n-publish:
    jobs:
      - hold:
          type: approval
      - build:
          publish: true
          requires:
            - hold

