FROM selenoid/base:5.0@@REQUIRES_JAVA@@

ARG VERSION
ARG CLEANUP
ARG APT_REPO
ARG PACKAGE

RUN  \
        ( [ "$CLEANUP" != "true" ] && rm -f /etc/apt/apt.conf.d/docker-clean ) || true && \
        apt-get update && \
        # This is needed as the current Ubuntu version lacks add-apt-repository
        apt-get install -y software-properties-common && \
        apt-get update && \
        add-apt-repository -y $APT_REPO && \
        apt-get update && \
        apt-get -y --no-install-recommends install $PACKAGE=$VERSION && \
        ( [ "$PACKAGE" = "firefox-trunk" ] && ln -s /usr/lib/$PACKAGE/$PACKAGE /usr/bin/firefox ) || true && \
        ($CLEANUP && rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*) || true
